language: perl
perl:
  - "5.14" 
  - "5.18"
  - "5.22"
  - "5.26"
sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - export DIST_INKT_PROFILE="Dist::Inkt::Profile::KJETILK"
  - eval $(curl https://travis-perl.github.io/init) --auto
notifications:
  irc: "irc://irc.perl.org/#perlrdf"

